plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.1.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0")
implementation "androidx.compose.animation:animation:1.6.0"
implementation "androidx.navigation:navigation-compose:2.7.0"
implementation "com.google.accompanist:accompanist-navigation-animation:0.32.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
