plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.janiplayer"
    compileSdk 34

implementation "androidx.compose.animation:animation:1.6.0"
implementation "androidx.navigation:navigation-compose:2.7.0"
implementation "com.google.accompanist:accompanist-navigation-animation:0.32.0"
    
    defaultConfig {
        applicationId "com.janiplayer"
        minSdk 26
        targetSdk 34

        versionCode 1
        versionName "1.0.0"

        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        release {
            storeFile file("janiplayer.keystore")
            storePassword "jelszo"
            keyAlias "janiplayer"
            keyPassword "jelszo"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true
            shrinkResources true

            proguardFiles getDefaultProguardFile(
                    "proguard-android-optimize.txt"
            ), "proguard-rules.pro"
        }

        debug {
            minifyEnabled false
            shrinkResources false
        }
    }
}
