name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Java beállítása
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle engedélyezése
        run: chmod +x ./gradlew

      - name: APK build
        run: ./gradlew assembleDebug

      - name: APK feltöltése
        uses: actions/upload-artifact@v3
        with:
          name: JaniPlayerMinimal-APK
          path: app/build/outputs/apk/debug/app-debug.apk
